### ISSUE TITLE
ASUS ProArt Z490 everything works on Catalina

### ISSUE THREAD

**Issue by theromis** [xiaovie/-Hackintosh-i7-10700k-ROG-STRIX-Z490-A-GAMING-RX-590.zip#1]
Want to say thank you for this great archive, which works from the box on my ASUS ProArt Z490, all USB ports works fine,
works even HDMI but loosing synchronizations once logins screen comes up, don't know how to debug it :( will try to reinstall may be it conflicts with NVIDIA web drivers.

**Comment by theromis** [comment]
after NVIDIA card removal nothing changed :(

**Comment by theromis** [comment]
DP configuration through TB3 works, ACPI does not go to sleep, but screen looses sync and it not returns from sleep.

**Comment by xiaovie** [comment]
hey bro，try this https://www.youtube.com/watch?v=wCs_IgFlYds
I made a lazy dmg system, please check the video guide I made


Roman Vasilyev <notifications@github.com> 于2020年11月3日周二 下午5:02写道：

**Comment by xiaovie** [comment]
> after NVIDIA card removal nothing changed :(

You can't use NVIDIA's latest graphics card on the 10.15 system version, and older graphics cards cannot be used either.
You need to use a DP or HDMI cable UHD630 to connect your monitor and shield the NVIDIA graphics card. You can use this method to shield the NVIDIA graphics card.
https://raw.githubusercontent.com/xiaovie/-Hackintosh-i7-10700k-ROG-STRIX-Z490-A-GAMING-RX-590.zip/master/Shield%20Nvidia%20Graphics.png

**Comment by theromis** [comment]
Thank you for this great job, at list everything works great, will try your suggestion and will share my results.

**Comment by xiaovie** [comment]
> Thank you for this great job, at list everything works great, will try your suggestion and will share my results.

Check your email roman@lonje.com, I sent you an email

**Comment by theromis** [comment]
I saw it, thank you for direct contact, DP works fine with nvidia card connected, so I think to buy Radeon 6800/6900 once somebody will prove it works on MacOS, I think it will be my last issue fix on hackintosh, my motherboard even returns from suspend with long delay but it hangs on loading something (spinning circrle) and stops on black screen. Sounds like this is the last problem which is very hard to fix :(

**Comment by xiaovie** [comment]
My native language is not English. Can you take a video of the malfunction
and send it to my email? The important thing is that you can only use
Nvidia's GTX1000 in the 10.13 system version. In any case, I don't
recommend that you use Nvidia graphics on the 10.15 system. AMD6000
graphics support may work in the fall of next year. The imac product line
will continue to use Intel x86 processors, I think next year’s new imac
will use AMD6000 graphics cards

Roman Vasilyev <notifications@github.com> 于2020年11月5日周四 上午11:27写道：

**Comment by theromis** [comment]
some how lost your reply, I just disabled suspend in settings and my desktop works fine

BTW:
1) your latest(2.4.9) update broke my usb setup, could you recommend me something to make it work as in `2.4.5`?
2) you have chinese language by deafult in your plist, is it possible to add "english" plist as an option?

**Comment by theromis** [comment]
everything works on 2.4.9 thank you, my problem was a faulty nvme drive
